name: mobile_app
description: CoFridge application.

dependencies:
  flutter:
    sdk: flutter
  barcode_scan:
  map_view:
  shared_preferences:
  connectivity:
  share:
  http:
  cached_network_image:
  url_launcher:
  flutter_webview_plugin:
  carousel:
  cupertino_icons:
  json_annotation:

dev_dependencies:
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
      - asset/img/fridge.png
