name: cofridge
description: CoFridge application.

dependencies:
  flutter:
    sdk: flutter
  barcode_scan:
  shared_preferences:
  connectivity:
  share:
  http:
  html:
  flutter_html_view:
  cached_network_image:
  url_launcher:
  carousel:
  cupertino_icons:
  json_annotation:

dev_dependencies:
  build_runner:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
      - asset/img/fridge.png
